Interview rita silva
Mobwiser-IT-Academy/algorithms-interview pull request #7
Opened 2020-09-18 03:02 UTC by RitaSilva28

2020-09-21 12:16 UTC, fabioaarito requested changes

2020-09-21 12:16 UTC, fabioaarito commented on questions/question-1/index.js
> +<<<<<<< HEAD
Olá @RitaSilva28. A validação do pull request falhou mas acho que é mais porque tens conflitos não resolvidos no teu pull request como podes ver aqui.

2020-09-21 13:24 UTC, RitaSilva28 commented on questions/question-1/index.js
> +<<<<<<< HEAD
Ola fabio! Hmmm ok quando chegar vou dar uma vista de olhos no PC estou a ver pelo tlm e nao tou a perceber muito bem..

2020-09-21 22:05 UTC, fabioaarito requested changes

2020-09-21 22:05 UTC, fabioaarito commented on questions/question-5/index.js
> +  var number = list.pop();
Na verdade este exercicio não está correto porque só estas a fazer unshift 1 vez logo a tua lista ficará [5,1,2,3,4] e sendo o n = 2 o objetivo seria fazer unshift 2 vezes e o output seria [4,5,1,2,3]. Se o n fosse 3 então o output já deveria ser [3,4,5,1,2]. 

Na verdade tenho de perceber como é que o validador está a dizer que o exercicio está correto :P

2020-12-05 17:50 UTC, fabioaarito commented
Interview validated successfully!

2020-12-05 17:50 UTC, closed without merging